name: animated_infinite_list
description: A library for making scroll view with animated pagination
version: 0.0.1
repository: https://github.com/nullskill/animated_infinite_list/tree/master
issue_tracker: https://github.com/nullskill/animated_infinite_list/issues
homepage: https://github.com/nullskill/animated_infinite_list

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
